name: ARN Webhook QA Test

on:
  workflow_dispatch:

jobs:
  trigger-arn:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ARN webhook
        run: |
          echo "Calling ARN webhook from GitHub Actions"
          curl -v --http1.1 -X post \
            -H "User-Agent: curl" \
            -H "Accept: application/json" \
            "https://arn-qa.upraise.io/arn/executewebhook/8d570e0c-14ec-4d9d-ace9-8fbe306e268c"
