name: ARN Webhook QA Test

on:
  workflow_dispatch:

jobs:
  trigger-arn:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ARN webhook
        run: |
          echo "Calling ARN webhook from GitHub Actions"
          curl -v --http1.1 -X GET \
            -H "User-Agent: curl" \
            -H "Accept: application/json" \
            "https://arn-qa.upraise.io/arn/executewebhook/45c29be5-f1f1-4aa4-a090-a2c63567adf2?version=10806"
