name: ARN Webhook QA Test

on:
  workflow_dispatch:

jobs:
  trigger-arn:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ARN webhook
        run: |
          echo "Calling ARN webhook from GitHub Actions"
          curl -v --http1.1 -X GET \
            -H "User-Agent: curl" \
            -H "Accept: application/json" \
            "https://arn-qa.upraise.io/arn/executewebhook/f97f646a-9f93-4a41-9cdb-06a36c5b6470?version=10806"
